name: Deploy Application

on:
  push:
    branches: [ "Development" ]  # or your default branch
  pull_request:
    branches: [ "Development" ]

jobs:
  build-and-deploy:
    if: github.repository == 'ElaXan/Handbook-Finder'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build

      # Add deployment steps here. For example, if deploying to a server:
      - name: Deploy and restart server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ${{ secret.PROJECT_PATH }}

            git checkout Development
            git pull origin Development
            yarn install --frozen-lockfile
            yarn build || exit 1
            screen -X -S handbook quit || true

            screen -dmS handbook bash -c 'serve dist -l 3000'
